#cloud-config

coreos:
  etcd:
    addr: $private_ipv4:4001
    peer-addr: $private_ipv4:7001

  fleet:
    metadata: region=us-west,role=master

  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start

# TODO: Organize these into targets.
    - name: kubernetes-master-params.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Configuration Fetcher
        Requires=network-online.target
        After=network-online.target

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/bin/curl --fail --silent --show-error \
        -H "X-Google-Metadata-Request: True" \
        -o /etc/kubernetes-master-params \
        http://169.254.169.254/computeMetadata/v1/instance/attributes/kubernetes-master-params

    - name: kubernetes-install-master.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Installer Scripts
        Requires=network-online.target
        After=network-online.target
        Requires=kubernetes-master-params.service
        After=kubernetes-master-params.service

        [Service]
        Type=oneshot
        RemainAfterExit=yes
        EnvironmentFile=/etc/kubernetes-master-params
        ExecStartPre=/usr/bin/mkdir -p /opt/kubernetes/pkg
        ExecStartPre=/usr/bin/curl --location --create-dirs --output /opt/kubernetes/pkg/kubernetes-server-linux-amd64.tar.gz ${SERVER_BINARY_TAR_URL}
        ExecStart=/usr/bin/tar xf /opt/kubernetes/pkg/kubernetes-server-linux-amd64.tar.gz -C /opt --overwrite

# FIXME: This config has no auth :(
    - name: kube-apiserver.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes API Server
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=etcd.service
        Requires=kubernetes-install-master.service
        Requires=kubernetes-master-params.service
        After=etcd.service
        After=kubernetes-install-master.service
        After=kubernetes-master-params.service

        [Service]
        EnvironmentFile=/etc/kubernetes-master-params
        ExecStart=/opt/kubernetes/server/bin/kube-apiserver \
            --address=0.0.0.0 \
            --port=8080 \
            --etcd_servers=http://$private_ipv4:4001 \
            --cloud_provider=gce \
            --allow_privileged=false \
            --portal_net=${PORTAL_NET} \
            --logtostderr=true

    - name: kube-scheduler.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Scheduler
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=kubernetes-install-master.service
        Requires=kubernetes-master-params.service
        Requires=kube-apiserver.service
        After=kubernetes-install-master.service
        After=kubernetes-master-params.service
        After=kube-apiserver.service

        [Service]
        ExecStart=/opt/kubernetes/server/bin/kube-scheduler \
            --master=127.0.0.1:8080 \
            --logtostderr=true
        Restart=always
        RestartSec=10

    - name: kube-controller-manager.service
      command: start
      content: |
        [Unit]
        Description=Kubernetes Controller Manager
        Documentation=https://github.com/GoogleCloudPlatform/kubernetes
        Requires=kubernetes-install-master.service
        Requires=kubernetes-master-params.service
        Requires=kube-apiserver.service
        After=kubernetes-install-master.service
        After=kubernetes-master-params.service
        After=kube-apiserver.service

        [Service]
        ExecStart=/opt/kubernetes/server/bin/kube-controller-manager \
            --master=127.0.0.1:8080 \
            --cloud_provider=gce \
            --minion_regexp='kubernetes-minion.*' \
            --logtostderr=true
        Restart=always
        RestartSec=10
